version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_local_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
